apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscar-sample-api
  labels:
    app: oscar-sample-api
    component: api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 75%
  selector:
    matchLabels:
      app: oscar-sample-api
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: oscar-sample-api
        component: api
    spec:
      containers:
      - name: oscar-sample-api
        image: ghcr.io/stefanprodan/podinfo:6.6.2
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        envFrom:
        - configMapRef:
            name: oscar-sample-api
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
