apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oscar-sample-api
  labels:
    app: oscar-sample-api
    component: api
spec:
  scaleTargetRef:
    kind: Deployment
    name: oscar-sample-api
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 2

