apiVersion: v1
kind: Service
metadata:
  name: sample-api
  labels:
    app: sample-api
    component: api
spec:
  selector:
    app: sample-api
  ports:
  - name: http
    port: 9898
    targetPort: http
    protocol: TCP
